export const GOOGLE_FONTS = [
    "Roboto",
    "Open Sans",
    "Noto Sans JP",
    "Lato",
    "Montserrat",
    "Roboto Condensed",
    "Source Sans Pro",
    "Poppins",
    "Oswald",
    "Roboto Mono",
    "Raleway",
    "Noto Sans",
    "Merriweather",
    "Nunito",
    "Ubuntu",
    "PT Sans",
    "Roboto Slab",
    "Playfair Display",
    "Rubik",
    "Inter",
    "Noto Sans KR",
    "Open Sans Condensed",
    "Lora",
    "Mukta",
    "Work Sans",
    "Nunito Sans",
    "PT Serif",
    "Quicksand",
    "Fira Sans",
    "Nanum Gothic",
    "Titillium Web",
    "Hind Siliguri",
    "Noto Serif",
    "Barlow",
    "Noto Sans TC",
    "Karla",
    "Inconsolata",
    "Heebo",
    "Libre Franklin",
    "Libre Baskerville",
    "Dosis",
    "IBM Plex Sans",
    "PT Sans Narrow",
    "Arimo",
    "Source Code Pro",
    "Josefin Sans",
    "Cabin",
    "Mulish",
    "Oxygen",
    "Bitter",
    "Dancing Script",
    "EB Garamond",
    "DM Sans",
    "Bebas Neue",
    "Anton",
    "Lobster",
    "Varela Round",
    "Source Serif Pro",
    "Cairo",
    "Noto Sans SC",
    "Hind",
    "Prompt",
    "Barlow Condensed",
    "Abel",
    "Comfortaa",
    "Fjalla One",
    "Arvo",
    "Exo 2",
    "Kanit",
    "Merriweather Sans",
    "Pacifico",
    "Architects Daughter",
    "Yanone Kaffeesatz",
    "Signika Negative",
    "Overpass",
    "Maven Pro",
    "Teko",
    "Asap",
    "Indie Flower",
    "Shadows Into Light",
    "Balsamiq Sans",
    "Manrope",
    "Slabo 27px",
    "Hind Madurai",
    "Abril Fatface",
    "Cormorant Garamond",
    "Questrial",
    "Noto Serif JP",
    "IBM Plex Serif",
    "Assistant",
    "Rajdhani",
    "Saira Condensed",
    "Permanent Marker",
    "Patrick Hand",
    "Yellowtail",
    "Catamaran",
    "Fira Sans Condensed",
    "Caveat",
    "Exo",
    "Acme",
    "Domine",
    "Play",
    "Satisfy",
    "Archivo Narrow",
    "Tajawal",
    "Zilla Slab",
    "Spartan",
    "Amatic SC",
    "Alfa Slab One",
    "M PLUS Rounded 1c",
    "ABeeZee",
    "Bree Serif",
    "Signika",
    "Public Sans",
    "Secular One",
    "Nanum Myeongjo",
    "Fredoka One",
    "Jost",
    "Crete Round",
    "Patua One",
    "Space Mono",
    "Cookie",
    "Vollkorn",
    "Alegreya Sans",
    "Righteous",
    "Noto Sans HK",
    "Padauk",
    "Martel",
    "Barlow Semi Condensed",
    "Archivo",
    "Cinzel",
    "Sarabun",
    "Space Grotesk",
    "Amiri",
    "Chakra Petch",
    "Antic Slab",
    "Courgette",
    "Crimson Pro",
    "Red Hat Display",
    "Prata",
    "Didact Gothic",
    "IBM Plex Mono",
    "DM Serif Display",
    "M PLUS 1p",
    "Ubuntu Condensed",
    "Alegreya",
    "Tinos",
    "Lobster Two",
    "Great Vibes",
    "Spectral",
    "Archivo Black",
    "PT Sans Caption",
    "Old Standard TT",
    "Kalam",
    "Almarai",
    "Kaushan Script",
    "Recursive",
    "Gothic A1",
    "Frank Ruhl Libre",
    "Eczar",
    "Francois One",
    "Cardo",
    "Parisienne",
    "Russo One",
    "Montserrat Alternates",
    "Encode Sans",
    "Yantramanav",
    "Noticia Text",
    "Baloo 2",
    "Passion One",
    "Staatliches",
    "Asap Condensed",
    "Quattrocento Sans",
    "Pathway Gothic One",
    "Gloria Hallelujah",
    "Sacramento",
    "Orbitron",
    "Luckiest Guy",
    "Rokkitt",
    "Changa",
    "Noto Kufi Arabic",
    "Concert One",
    "Cuprum",
    "Josefin Slab",
    "Volkhov",
    "Special Elite",
    "Cormorant",
    "Chivo",
    "Paytone One",
    "Cantarell",
    "Taviraj",
    "Noto Serif TC",
    "Unna",
    "Quattrocento",
    "Faustina",
    "PT Mono",
    "News Cycle",
    "Neuton",
    "Poiret One",
    "Hammersmith One",
    "Vidaloka",
    "Carter One",
    "Sawarabi Mincho",
    "Bangers",
    "Syncopate",
    "Khand",
    "Playfair Display SC",
    "Merienda",
    "Alata",
    "Press Start 2P",
    "Ropa Sans",
    "Philosopher",
    "Advent Pro",
    "Playball",
    "Marcellus",
    "Aleo",
    "Ultra",
    "Handlee",
    "Saira",
    "Noto Serif KR",
    "Gelasio",
    "Sanchez",
    "Monda",
    "Arima Madurai",
    "Fira Sans Extra Condensed",
    "Sigmar One",
    "Alice",
    "Lusitana",
    "Tangerine",
    "Marck Script",
    "Istok Web",
    "Sora",
    "Actor",
    "Ubuntu Mono",
    "Nanum Gothic Coding",
    "Mali",
    "Cabin Condensed",
    "DM Serif Text",
    "Homemade Apple",
    "Gudea",
    "Arapey",
    "Karma",
    "Nanum Pen Script",
    "Titan One",
    "Mitr",
    "Sawarabi Gothic",
    "Yeseva One",
    "Palanquin",
    "Allura",
    "Neucha",
    "Ruda",
    "Be Vietnam Pro",
    "Amaranth",
    "Itim",
    "El Messiri",
    "Adamina",
    "Viga",
    "Noto Serif SC",
    "Jura",
    "Lexend Deca",
    "Bungee",
    "Abhaya Libre",
    "Economica",
    "Khula",
    "Mr Dafoe",
    "Hind Vadodara",
    "Lilita One",
    "Unica One",
    "Gentium Basic",
    "Saira Semi Condensed",
    "Rock Salt",
    "BenchNine",
    "Sen",
    "Mate SC",
    "Bai Jamjuree",
    "Aclonica",
    "Gochi Hand",
    "Pragati Narrow",
    "Courier Prime",
    "Sarala",
    "Monoton",
    "Audiowide",
    "Alef",
    "Bad Script",
    "Oleo Script",
    "Varela",
    "IM Fell English SC",
    "Creepster",
    "Sorts Mill Goudy",
    "Gentium Book Basic",
    "Julius Sans One",
    "Pontano Sans",
    "Quantico",
    "Armata",
    "Cousine",
    "Alex Brush",
    "Share Tech Mono",
    "Tenor Sans",
    "Arsenal",
    "Kosugi Maru",
    "Ramabhadra",
    "Nothing You Could Do",
    "Mukta Malar",
    "Suez One",
    "Red Hat Text",
    "Fugaz One",
    "Electrolize",
    "Rufina",
    "Allerta",
    "Lalezar",
    "Gruppo",
    "Shadows Into Light Two",
    "IBM Plex Sans Condensed",
    "Cantata One",
    "Damion",
    "Pangolin",
    "Commissioner",
    "Bubblegum Sans",
    "Sriracha",
    "Encode Sans Condensed",
    "Changa One",
    "Basic",
    "Reenie Beanie",
    "Martel Sans",
    "Fira Mono",
    "Mada",
    "Rubik Mono One",
    "Forum",
    "Bowlby One SC",
    "Annie Use Your Telescope",
    "Italianno",
    "Black Ops One",
    "Yrsa",
    "Average",
    "Norican",
    "Anonymous Pro",
    "Days One",
    "Jaldi",
    "Blinker",
    "Mandali",
    "Sintony",
    "Voltaire",
    "Pinyon Script",
    "Overlock",
    "Squada One",
    "Candal",
    "Coda",
    "Chewy",
    "Literata",
    "Krub",
    "Alegreya Sans SC",
    "Caveat Brush",
    "Rancho",
    "Berkshire Swash",
    "Niramit",
    "Glegoo",
    "Spinnaker",
    "Boogaloo",
    "Markazi Text",
    "Michroma",
    "Noto Naskh Arabic",
    "Kameron",
    "Shrikhand",
    "Judson",
    "VT323",
    "Kreon",
    "Bevan",
    "Enriqueta",
    "Fredericka the Great",
    "Sansita",
    "Rasa",
    "PT Serif Caption",
    "Black Han Sans",
    "Overpass Mono",
    "Darker Grotesque",
    "Six Caps",
    "Reem Kufi",
    "Londrina Solid",
    "Belgrano",
    "Hind Guntur",
    "Cabin Sketch",
    "Holtwood One SC",
    "Rambla",
    "Lemonada",
    "Knewave",
    "Pridi",
    "Bodoni Moda",
    "Coming Soon",
    "Arizonia",
    "Capriola",
    "Telex",
    "Laila",
    "Libre Caslon Text",
    "Aldrich",
    "Allerta Stencil",
    "Lexend",
    "Racing Sans One",
    "Niconne",
    "Palanquin Dark",
    "Rozha One",
    "Antic",
    "Alike Angular",
    "Covered By Your Grace",
    "Miriam Libre",
    "Mukta Vaani",
    "Castoro",
    "Epilogue",
    "Lateef",
    "Saira Extra Condensed",
    "Leckerli One",
    "GFS Didot",
    "Scada",
    "Graduate",
    "Arbutus Slab",
    "Comic Neue",
    "Mrs Saint Delafield",
    "Amita",
    "Gilda Display",
    "Suranna",
    "Herr Von Muellerhoff",
    "Cinzel Decorative",
    "Caudex",
    "Syne",
    "Kristi",
    "Baskervville",
    "Baloo Tamma 2",
    "Trocchi",
    "Mate",
    "Yesteryear",
    "Nanum Brush Script",
    "Rye",
    "Corben",
    "Oxanium",
    "Just Another Hand",
    "Charm",
    "Bowlby One",
    "Aladin",
    "Alatsi",
    "Delius",
    "K2D",
    "Alegreya SC",
    "Lustria",
    "Rochester",
    "Biryani",
    "Metrophobic",
    "Share",
    "Alike",
    "Copse",
    "Average Sans",
    "Magra",
    "Athiti",
    "Marcellus SC",
    "Cedarville Cursive",
    "Noto Sans Devanagari",
    "Bungee Inline",
    "Carme",
    "Nixie One",
    "Trirong",
    "Nobile",
    "Coustard",
    "Krona One",
    "Oranienbaum",
    "Fira Code",
    "Noto Sans Tamil",
    "Amethysta",
    "Stint Ultra Condensed",
    "Contrail One",
    "Duru Sans",
    "Skranji",
    "Seaweed Script",
    "Cormorant Infant",
    "Podkova",
    "Pattaya",
    "Jua",
    "Averia Serif Libre",
    "Kumbh Sans",
    "Fauna One",
    "Ovo",
    "Halant",
    "NTR",
    "Carrois Gothic",
    "Amiko",
    "JetBrains Mono",
    "Wallpoet",
    "La Belle Aurore",
    "Schoolbell",
    "Big Shoulders Display",
    "Petit Formal Script",
    "Belleza",
    "Maitree",
    "Cambay",
    "Rosario",
    "Calligraffitti",
    "Mr De Haviland",
    "Molengo",
    "Convergence",
    "Merienda One",
    "Libre Barcode 39",
    "Antonio",
    "Jockey One",
    "Sofia",
    "Kosugi",
    "Cutive Mono",
    "Grand Hotel",
    "Sunflower",
    "Chonburi",
    "Rammetto One",
    "Manjari",
    "Shippori Mincho",
    "Esteban",
    "Gugi",
    "Qwigley",
    "Georama",
    "Slabo 13px",
    "Oxygen Mono",
    "Do Hyeon",
    "IM Fell DW Pica",
    "Bellefair",
    "Kelly Slab",
    "Allan",
    "Marmelad",
    "Grandstander",
    "Monsieur La Doulaise",
    "Hanuman",
    "Hi Melody",
    "Montez",
    "Averia Libre",
    "Poly",
    "Buenard",
    "Sniglet",
    "Andika",
    "Stardos Stencil",
    "Thasadith",
    "BioRhyme",
    "Waiting for the Sunrise",
    "Marvel",
    "Chelsea Market",
    "Dawning of a New Day",
    "Farro",
    "Encode Sans Semi Condensed",
    "Hepta Slab",
    "Radley",
    "IM Fell English",
    "Harmattan",
    "Proza Libre",
    "Bentham",
    "Spectral SC",
    "Goudy Bookletter 1911",
    "Mallanna",
    "Kurale",
    "Cormorant SC",
    "Gabriela",
    "STIX Two Text",
    "David Libre",
    "Cutive",
    "Megrim",
    "Brawler",
    "Pompiere",
    "Lemon",
    "Coda Caption",
    "Sue Ellen Francisco",
    "Kadwa",
    "Bungee Shade",
    "Nova Mono",
    "Limelight",
    "Happy Monkey",
    "Mirza",
    "McLaren",
    "Lexend Exa",
    "Emilys Candy",
    "Poller One",
    "Zeyada",
    "UnifrakturMaguntia",
    "Prosto One",
    "Love Ya Like A Sister",
    "Fanwood Text",
    "Short Stack",
    "Quando",
    "Give You Glory",
    "B612 Mono",
    "Gravitas One",
    "Noto Sans Malayalam",
    "Irish Grover",
    "Rouge Script",
    "Inder",
    "Noto Sans Thai",
    "Grenze Gotisch",
    "Homenaje",
    "Oleo Script Swash Caps",
    "Azeret Mono",
    "Urbanist",
    "Tillana",
    "IM Fell Double Pica",
    "Mountains of Christmas",
    "Henny Penny",
    "Turret Road",
    "ZCOOL QingKe HuangYou",
    "Ceviche One",
    "Newsreader",
    "Oregano",
    "Rakkas",
    "Sarpanch",
    "ZCOOL XiaoWei",
    "Patrick Hand SC",
    "Clicker Script",
    "Inknut Antiqua",
    "Outfit",
    "Mouse Memoirs",
    "Freckle Face",
    "Euphoria Script",
    "Original Surfer",
    "Vast Shadow",
    "Baloo Thambi 2",
    "Over the Rainbow",
    "Finger Paint",
    "Praise",
    "Baloo Da 2",
    "DM Mono",
    "Mansalva",
    "Cambo",
    "Livvic",
    "Antic Didone",
    "Bellota Text",
    "Katibeh",
    "Major Mono Display",
    "Gurajada",
    "Aguafina Script",
    "Doppio One",
    "Gorditas",
    "Atma",
    "Fondamento",
    "Vesper Libre",
    "Battambang",
    "Nova Round",
    "Arya",
    "Galada",
    "Sail",
    "Ma Shan Zheng",
    "Expletus Sans",
    "Baloo Tammudu 2",
    "Big Shoulders Text",
    "Baumans",
    "Federo",
    "Walter Turncoat",
    "Noto Sans Kannada",
    "Cormorant Upright",
    "Geo",
    "Vollkorn SC",
    "Sedgwick Ave",
    "Noto Sans Hebrew",
    "Anaheim",
    "Ranchers",
    "Della Respira",
    "Unkempt",
    "Aref Ruqaa",
    "Share Tech",
    "Codystar",
    "Meddon",
    "Tenali Ramakrishna",
    "Raleway Dots",
    "Dokdo",
    "Noto Sans Bengali",
    "Italiana",
    "Noto Sans Telugu",
    "Atkinson Hyperlegible",
    "Crafty Girls",
    "Balthazar",
    "Mochiy Pop One",
    "Lekton",
    "Ephesis",
    "B612",
    "Faster One",
    "Timmana",
    "Kiwi Maru",
    "Metamorphous",
    "Calistoga",
    "Road Rage",
    "Ledger",
    "Mukta Mahee",
    "Shojumaru",
    "Caladea",
    "Trykker",
    "Chau Philomene One",
    "Just Me Again Down Here",
    "Delius Swash Caps",
    "Numans",
    "Bubbler One",
    "Notable",
    "Montserrat Subrayada",
    "Wendy One",
    "Lexend Zetta",
    "Noto Sans Oriya",
    "Dela Gothic One",
    "The Girl Next Door",
    "Tomorrow",
    "Mako",
    "Elsie",
    "Meera Inimai",
    "Orienta",
    "Yatra One",
    "Flamenco",
    "Amarante",
    "Baloo Paaji 2",
    "Frijole",
    "Averia Sans Libre",
    "Goblin One",
    "Odibee Sans",
    "Baloo Chettan 2",
    "Montaga",
    "Salsa",
    "Strait",
    "Noto Sans Mandaic",
    "Port Lligat Sans",
    "Headland One",
    "Fraunces",
    "Noto Sans Gurmukhi",
    "Noto Sans Gujarati",
    "Eater",
    "Coiny",
    "Bilbo Swash Caps",
    "Loved by the King",
    "Dynalight",
    "Fjord One",
    "Encode Sans Expanded",
    "Noto Serif Display",
    "Tienne",
    "RocknRoll One",
    "Asul",
    "Peralta",
    "Imprima",
    "Cherry Swash",
    "Ranga",
    "Scope One",
    "Libre Barcode 39 Text",
    "Englebert",
    "Gafata",
    "Reggae One",
    "Cherry Cream Soda",
    "Tauri",
    "Stalemate",
    "Shippori Mincho B1",
    "Artifika",
    "Ruslan Display",
    "Fresca",
    "Life Savers",
    "Wire One",
    "Carrois Gothic SC",
    "Style Script",
    "Pavanam",
    "Varta",
    "Manuale",
    "Lakki Reddy",
    "Slackey",
    "Spicy Rice",
    "UnifrakturCook",
    "Voces",
    "Port Lligat Slab",
    "Bilbo",
    "Vibur",
    "League Script",
    "Kodchasan",
    "Nova Square",
    "MuseoModerno",
    "MonteCarlo",
    "Kulim Park",
    "Comforter",
    "Mina",
    "Noto Sans Display",
    "Cantora One",
    "Rum Raisin",
    "M PLUS 1 Code",
    "Comforter Brush",
    "Delius Unicase",
    "KoHo",
    "Gaegu",
    "Yusei Magic",
    "Medula One",
    "Charmonman",
    "Iceland",
    "Noto Sans Sinhala",
    "Fahkwang",
    "Lily Script One",
    "Baloo Bhaina 2",
    "Song Myung",
    "Puritan",
    "Encode Sans Semi Expanded",
    "Almendra",
    "Denk One",
    "Kite One",
    "Goldman",
    "Trade Winds",
    "Kufam",
    "Sarina",
    "Habibi",
    "Stoke",
    "Engagement",
    "Kranky",
    "IM Fell French Canon",
    "Ibarra Real Nova",
    "Solway",
    "Besley",
    "Modak",
    "Saira Stencil One",
    "Margarine",
    "DotGothic16",
    "Lovers Quarrel",
    "Cormorant Unicase",
    "Sonsie One",
    "Milonga",
    "MedievalSharp",
    "Londrina Outline",
    "Paprika",
    "Libre Barcode 128",
    "Khmer",
    "Libre Barcode 39 Extended Text",
    "Meie Script",
    "New Rocker",
    "Gamja Flower",
    "Chango",
    "Akronim",
    "Mystery Quest",
    "Ribeye",
    "Libre Caslon Display",
    "Cute Font",
    "Sumana",
    "Prociono",
    "Jomhuria",
    "Dekko",
    "Fontdiner Swanky",
    "Ramaraja",
    "Simonetta",
    "Julee",
    "Shanti",
    "Macondo Swash Caps",
    "Yeon Sung",
    "Rationale",
    "Chicle",
    "Germania One",
    "IM Fell French Canon SC",
    "Rosarivo",
    "M PLUS 2",
    "Buda",
    "Overlock SC",
    "Barriecito",
    "Mogra",
    "Autour One",
    "Baloo Bhai 2",
    "ZCOOL KuaiLe",
    "Pirata One",
    "Sansita Swashed",
    "Crushed",
    "Zilla Slab Highlight",
    "Quintessential",
    "Asar",
    "Cagliostro",
    "Farsan",
    "Sancreek",
    "Uncial Antiqua",
    "Nokora",
    "Sulphur Point",
    "Fenix",
    "Text Me One",
    "IM Fell DW Pica SC",
    "Kotta One",
    "Piazzolla",
    "Condiment",
    "Inika",
    "Stint Ultra Expanded",
    "Bellota",
    "Ruluko",
    "Donegal One",
    "Allison",
    "Galindo",
    "Moul",
    "Nosifer",
    "Akaya Kanadaka",
    "IM Fell Great Primer",
    "Kavivanar",
    "Eagle Lake",
    "Offside",
    "Griffy",
    "Croissant One",
    "Iceberg",
    "Angkor",
    "Junge",
    "Big Shoulders Stencil Display",
    "Nova Flat",
    "Gayathri",
    "Ruthie",
    "Glory",
    "Swanky and Moo Moo",
    "Petrona",
    "Averia Gruesa Libre",
    "Rhodium Libre",
    "East Sea Dokdo",
    "Stylish",
    "Hachi Maru Pop",
    "Piedra",
    "Potta One",
    "Kumar One",
    "Sree Krushnadevaraya",
    "WindSong",
    "Bahiana",
    "Bigelow Rules",
    "Noto Sans Arabic",
    "Kantumruy",
    "Underdog",
    "Barrio",
    "Linden Hill",
    "Londrina Shadow",
    "Dorsa",
    "Noto Nastaliq Urdu",
    "Monofett",
    "Sura",
    "Inria Serif",
    "Almendra SC",
    "Marko One",
    "Modern Antiqua",
    "Tourney",
    "Wellfleet",
    "Zen Dots",
    "Redressed",
    "Akaya Telivigala",
    "Mrs Sheppards",
    "Vampiro One",
    "Kavoon",
    "Content",
    "Molle",
    "Maiden Orange",
    "Tulpen One",
    "Sirin Stencil",
    "Chathura",
    "Miniver",
    "Poor Story",
    "Chilanka",
    "Andika New Basic",
    "Ribeye Marrow",
    "Risque",
    "Spirax",
    "Devonshire",
    "Felipa",
    "Red Rose",
    "Rowdies",
    "Sahitya",
    "Galdeano",
    "Gotu",
    "Noto Sans Symbols",
    "Montagu Slab",
    "Joti One",
    "Scheherazade New",
    "Elsie Swash Caps",
    "Bayon",
    "Jomolhari",
    "Dangrek",
    "Lexend Mega",
    "Lancelot",
    "Metal Mania",
    "Girassol",
    "Viaoda Libre",
    "Zen Kaku Gothic New",
    "Lexend Giga",
    "Diplomata",
    "Shippori Antique",
    "Orelega One",
    "Stick",
    "Koulen",
    "Keania One",
    "Arbutus",
    "Kumar One Outline",
    "Beth Ellen",
    "Ravi Prakash",
    "Caesar Dressing",
    "Glass Antiqua",
    "Macondo",
    "Jolly Lodger",
    "Stick No Bills",
    "Brygada 1918",
    "Romanesco",
    "IM Fell Great Primer SC",
    "Fascinate Inline",
    "Libre Barcode 39 Extended",
    "Gupter",
    "Princess Sofia",
    "Revalia",
    "Libre Barcode 128 Text",
    "Smythe",
    "Atomic Age",
    "Jim Nightshade",
    "Train One",
    "Asset",
    "Ewert",
    "Hanalei Fill",
    "Bigshot One",
    "Srisakdi",
    "Odor Mean Chey",
    "Diplomata SC",
    "Jacques Francois Shadow",
    "Kaisei Tokumin",
    "Peddana",
    "Estonia",
    "Gemunu Libre",
    "Zen Old Mincho",
    "Londrina Sketch",
    "Plaster",
    "Inria Sans",
    "Jacques Francois",
    "Kirang Haerang",
    "Combo",
    "Snippet",
    "Dr Sugiyama",
    "Grenze",
    "Bungee Outline",
    "Fascinate",
    "Noto Sans Myanmar",
    "GFS Neohellenic",
    "Bona Nova",
    "Miss Fajardose",
    "Chela One",
    "Unlock",
    "Flavors",
    "Siemreap",
    "Oldenburg",
    "Festive",
    "Hahmlet",
    "Zhi Mang Xing",
    "Black And White Picture",
    "Seymour One",
    "Mr Bedfort",
    "Noto Sans Georgian",
    "Emblema One",
    "Purple Purse",
    "Almendra Display",
    "Nova Slim",
    "M PLUS 1",
    "Butterfly Kids",
    "Yaldevi",
    "Truculenta",
    "Smokum",
    "Metal",
    "Sunshiney",
    "Sedgwick Ave Display",
    "Kdam Thmor",
    "Fruktur",
    "Freehand",
    "IBM Plex Sans Thai",
    "Zen Loop",
    "Lexend Tera",
    "Passero One",
    "Miltonian Tattoo",
    "Bokor",
    "Erica One",
    "IBM Plex Sans Arabic",
    "Fuggles",
    "Bungee Hairline",
    "Ballet",
    "Rampart One",
    "Vibes",
    "IM Fell Double Pica SC",
    "Kaisei Opti",
    "Big Shoulders Stencil Text",
    "Kaisei Decol",
    "Zen Maru Gothic",
    "Liu Jian Mao Cao",
    "Red Hat Mono",
    "Preahvihear",
    "Snowburst One",
    "Hanalei",
    "Otomanopee One",
    "Gidugu",
    "Hina Mincho",
    "Yomogi",
    "Klee One",
    "Bonbon",
    "Noto Sans Mono",
    "Gowun Batang",
    "Chenla",
    "Texturina",
    "Noto Sans Armenian",
    "Nerko One",
    "Zen Antique",
    "Stalinist One",
    "Bahianita",
    "Karantina",
    "Ruge Boogie",
    "Supermercado One",
    "Butcherman",
    "Noto Sans Gothic",
    "Trochut",
    "Lacquer",
    "Benne",
    "Federant",
    "Kaisei HarunoUmi",
    "Astloch",
    "Petemoss",
    "Bonheur Royale",
    "Gluten",
    "Miltonian",
    "Suwannaphum",
    "Long Cang",
    "Geostar Fill",
    "Sofadi One",
    "Moulpali",
    "Aubrey",
    "Zen Kaku Gothic Antique",
    "Nova Cut",
    "Single Day",
    "Sevillana",
    "Andada Pro",
    "Syne Mono",
    "Nova Oval",
    "Nova Script",
    "New Tegomin",
    "Genos",
    "Taprom",
    "Suravaram",
    "Zen Kurenaido",
    "Dongle",
    "Xanh Mono",
    "Birthstone Bounce",
    "IBM Plex Sans KR",
    "Encode Sans SC",
    "BioRhyme Expanded",
    "Imbue",
    "Carattere",
    "Dhurjati",
    "Mohave",
    "Kings",
    "Birthstone",
    "Noto Serif Bengali",
    "Alumni Sans",
    "Trispace",
    "Mochiy Pop P One",
    "Zen Antique Soft",
    "Gowun Dodum",
    "Fasthand",
    "Lexend Peta",
    "Shalimar",
    "Big Shoulders Inline Text",
    "Hurricane",
    "M PLUS Code Latin",
    "Flow Circular",
    "Langar",
    "Kenia",
    "Flow Rounded",
    "Fleur De Leah",
    "Cherish",
    "Flow Block",
    "Geostar",
    "Noto Serif Tamil",
    "Qahiri",
    "Grechen Fuemen",
    "Libre Barcode EAN13 Text",
    "Are You Serious",
    "Zen Tokyo Zoo",
    "Noto Sans Tamil Supplement",
    "Sassy Frass",
    "Puppies Play",
    "Warnes",
    "Big Shoulders Inline Display",
    "Passions Conflict",
    "Yuji Boku",
    "Rubik Beastly",
    "Grey Qo",
    "Yuji Syuku",
    "IBM Plex Sans Thai Looped",
    "Syne Tactile",
    "Gideon Roman",
    "Shippori Antique B1",
    "Explora",
    "Caramel",
    "Koh Santepheap",
    "Yuji Mai",
    "Oi",
    "IBM Plex Sans Hebrew",
    "Palette Mosaic",
    "IBM Plex Sans Devanagari",
    "Noto Sans Coptic",
    "Noto Sans Tai Viet",
    "Uchen",
    "Noto Serif Georgian",
    "Noto Sans Lao",
    "Noto Sans Khmer",
    "Noto Sans Deseret",
    "Noto Serif Thai",
    "Noto Serif Armenian",
    "Noto Sans Javanese",
    "Noto Serif Malayalam",
    "Noto Sans Brahmi",
    "Noto Serif Ethiopic",
    "Noto Sans Thai Looped",
    "Noto Sans Imperial Aramaic",
    "Noto Serif Devanagari",
    "Noto Sans Tagalog",
    "Noto Serif Lao",
    "Noto Sans Cherokee",
    "Noto Sans Thaana",
    "Noto Serif Khmer",
    "Noto Serif Hebrew",
    "Noto Sans Cypriot",
    "Noto Serif Gujarati",
    "Noto Sans Ol Chiki",
    "Noto Rashi Hebrew",
    "Noto Sans Old Turkic",
    "Noto Sans Cham",
    "Noto Serif Sinhala",
    "Noto Music",
    "Noto Serif Kannada",
    "Noto Sans Canadian Aboriginal",
    "Noto Sans Carian",
    "Noto Sans Meetei Mayek",
    "Noto Serif Gurmukhi",
    "Noto Serif Tibetan",
    "Noto Serif Myanmar",
    "Noto Sans Old Italic",
    "Noto Sans Mongolian",
    "Noto Sans Balinese",
    "Noto Sans Sundanese",
    "Noto Sans Sora Sompeng",
    "Noto Serif Telugu",
    "Noto Sans Tifinagh",
    "Noto Sans Osmanya",
    "Noto Serif Yezidi",
    "Noto Sans Cuneiform",
    "Noto Serif Nyiakeng Puachue Hmong",
    "Noto Sans Lisu",
    "Noto Sans Adlam",
    "Noto Sans Adlam Unjoined",
    "Noto Sans Bamum",
    "Noto Sans Saurashtra",
    "Noto Sans Tai Tham",
    "Noto Sans Old Hungarian",
    "Noto Sans Hanifi Rohingya",
    "Noto Sans Grantha",
    "Noto Sans Kayah Li",
    "Noto Sans Medefaidrin",
    "Noto Sans Egyptian Hieroglyphs",
    "Noto Sans Inscriptional Parthian",
    "Noto Sans Anatolian Hieroglyphs",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Samaritan",
    "Noto Sans Linear B",
    "Noto Sans Caucasian Albanian",
    "Noto Sans Syriac",
    "Noto Sans Palmyrene",
    "Noto Sans Phoenician",
    "Noto Sans Symbols 2",
    "Noto Sans Old South Arabian",
    "Noto Sans Kaithi",
    "Noto Serif Balinese",
    "Noto Sans Hanunoo",
    "Noto Serif Dogra",
    "Noto Sans Old Persian",
    "Noto Serif Grantha",
    "Noto Sans Kharoshthi",
    "Noto Sans Old North Arabian",
    "Noto Sans Avestan",
    "Noto Sans Tai Le",
    "Noto Serif Ahom",
    "Noto Sans Math",
    "Noto Sans Batak",
    "Noto Sans Runic",
    "Noto Sans Yi",
    "Noto Serif Tangut",
    "Noto Sans New Tai Lue",
    "Noto Sans Tirhuta",
    "Noto Sans Mayan Numerals",
    "Noto Sans Limbu",
    "Noto Sans Old Permic",
    "Noto Sans Multani",
    "Noto Sans Zanabazar Square",
    "Noto Sans Syloti Nagri",
    "Noto Traditional Nushu",
    "Noto Sans Elbasan",
    "Noto Sans Pau Cin Hau",
    "Noto Sans Shavian",
    "Noto Sans Rejang",
    "Noto Sans Glagolitic",
    "Noto Sans Buginese",
    "Noto Sans Mahajani",
    "Noto Sans Meroitic",
    "Noto Sans Marchen",
    "Noto Sans Nushu",
    "Noto Sans Newa",
    "Noto Sans Hatran",
    "Noto Sans Buhid",
    "Noto Sans Indic Siyaq Numbers",
    "Noto Sans Nabataean",
    "Noto Sans Chakma",
    "Noto Sans Bassa Vah",
    "Noto Sans Manichaean",
    "Noto Sans Psalter Pahlavi",
    "Noto Sans Tagbanwa",
    "Noto Sans Old Sogdian",
    "Noto Sans Pahawh Hmong",
    "Noto Sans Duployan",
    "Noto Sans Ugaritic",
    "Noto Sans Lepcha",
    "Noto Sans Osage",
    "Noto Sans Masaram Gondi",
    "Noto Sans Soyombo",
    "Noto Sans Takri",
    "Noto Sans Mro",
    "Noto Sans Sogdian",
    "Noto Sans Lycian",
    "Noto Sans Gunjala Gondi",
    "Noto Sans Ogham",
    "Noto Sans Elymaic",
    "Noto Sans Phags Pa",
    "Noto Sans Bhaiksuki",
    "Noto Sans Siddham",
    "Noto Sans Warang Citi",
    "Noto Sans N Ko",
    "Noto Sans Khojki",
    "Noto Sans Modi",
    "Noto Sans Miao",
    "Noto Sans Sharada",
    "Noto Sans Vai",
    "Noto Sans Linear A",
    "Noto Sans Lydian",
    "Noto Sans Wancho",
    "Noto Sans Khudawadi",
    "Baloo Bhaijaan 2",
    "Corinthia",
    "Fuzzy Bubbles",
    "Gwendolyn",
    "Luxurious Script",
    "Meow Script",
    "Murecho",
    "Readex Pro",
    "Redacted",
    "Redacted Script",
    "Smooch",
    "Source Sans 3"
];